apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: boilerplate-random
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2.4-alpine
          imagePullPolicy: IfNotPresent
          command: ["redis-server", "--port", "24111"]
          ports:
            - name: redis
              containerPort: 24111
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: boilerplate-random
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 24111
      targetPort: redis
